# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-18 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendedflatpage',
            name='slug',
            field=models.SlugField(default='test'),
            preserve_default=False,
        ),
    ]
