# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-19 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_extendedflatpage_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendedflatpage',
            name='description_en',
            field=models.CharField(max_length=255, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='extendedflatpage',
            name='description_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='extendedflatpage',
            name='keywords_en',
            field=models.CharField(max_length=255, null=True, verbose_name='keywords'),
        ),
        migrations.AddField(
            model_name='extendedflatpage',
            name='keywords_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='keywords'),
        ),
    ]
