# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-28 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20170619_2022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extendedflatpage',
            name='description',
        ),
        migrations.RemoveField(
            model_name='extendedflatpage',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='extendedflatpage',
            name='description_ru',
        ),
        migrations.AddField(
            model_name='extendedflatpage',
            name='meta_description',
            field=models.CharField(default='desc', max_length=255, verbose_name='meta_description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='extendedflatpage',
            name='meta_description_en',
            field=models.CharField(max_length=255, null=True, verbose_name='meta_description'),
        ),
        migrations.AddField(
            model_name='extendedflatpage',
            name='meta_description_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='meta_description'),
        ),
    ]
