# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-08 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='ip',
            field=models.GenericIPAddressField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='email',
            name='subject',
            field=models.CharField(db_index=True, default='Email from client', max_length=255, verbose_name='subject'),
        ),
        migrations.AlterField(
            model_name='email',
            name='contacts',
            field=models.CharField(db_index=True, max_length=255, verbose_name='contacts'),
        ),
        migrations.AlterField(
            model_name='email',
            name='is_readed',
            field=models.BooleanField(db_index=True, default=False, verbose_name='is default?'),
        ),
        migrations.AlterField(
            model_name='email',
            name='name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='email',
            name='text',
            field=models.TextField(db_index=True, max_length=255, verbose_name='text'),
        ),
    ]
