# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-08 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_auto_20170908_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='is_readed',
            field=models.BooleanField(db_index=True, default=False, verbose_name='is readed?'),
        ),
    ]
