# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-23 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0002_auto_20170623_1608'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='technology',
            options={'get_latest_by': 'modified', 'ordering': ('title',), 'verbose_name_plural': 'technologies'},
        ),
        migrations.AlterField(
            model_name='technology',
            name='slug',
            field=models.SlugField(),
        ),
    ]
