# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-28 14:00
from __future__ import unicode_literals

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0003_auto_20170623_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.CharField(max_length=255, verbose_name='keywords')),
                ('meta_description', models.CharField(max_length=255, verbose_name='meta_description')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False)),
                ('content', models.TextField(verbose_name='content')),
                ('technologies', models.ManyToManyField(related_name='technologies', to='works.Technology', verbose_name='technologies')),
            ],
            options={
                'get_latest_by': 'modified',
            },
        ),
    ]
