# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-28 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0004_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='work',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='work',
            name='keywords_en',
            field=models.CharField(max_length=255, null=True, verbose_name='keywords'),
        ),
        migrations.AddField(
            model_name='work',
            name='keywords_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='keywords'),
        ),
        migrations.AddField(
            model_name='work',
            name='meta_description_en',
            field=models.CharField(max_length=255, null=True, verbose_name='meta_description'),
        ),
        migrations.AddField(
            model_name='work',
            name='meta_description_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='meta_description'),
        ),
        migrations.AddField(
            model_name='work',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='work',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
    ]
