# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-28 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0005_auto_20170628_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='content_en',
            field=models.TextField(null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='work',
            name='content_ru',
            field=models.TextField(null=True, verbose_name='content'),
        ),
    ]
