# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-28 14:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0006_auto_20170628_1717'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='work',
            options={'ordering': ('order',)},
        ),
    ]
