# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-11 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0008_auto_20170628_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='technology',
            name='works',
            field=models.ManyToManyField(related_name='works', to='works.Work', verbose_name='works'),
        ),
    ]
