# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-05 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0009_technology_works'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='is_enabled',
            field=models.BooleanField(db_index=True, default=True, verbose_name='is enabled'),
        ),
    ]
