# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-05 14:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0010_work_is_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False)),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('is_default', models.BooleanField(default=False, verbose_name='is default?')),
                ('photo', imagekit.models.fields.ProcessedImageField(upload_to='works_photos', verbose_name='photo')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='works.Work')),
            ],
            options={
                'ordering': ['-is_default'],
            },
        ),
    ]
