# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-05 15:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0012_auto_20170905_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='works.Work'),
        ),
    ]
